model_list:
  - model_name: google/gemini-3-flash-preview # Context length: 1,048,576
    litellm_params:
      model: openrouter/google/gemini-3-flash-preview
      api_base: https://openrouter.ai/api/v1
      api_key: "os.environ/OPEN_ROUTER_API_KEY"
  - model_name: deepseek/deepseek-v4-pro # Context length: 1M
    litellm_params:
      model: openrouter/deepseek/deepseek-v4-pro
      api_base: https://openrouter.ai/api/v1
      api_key: "os.environ/OPEN_ROUTER_API_KEY"
  - model_name: deepseek/deepseek-v4-flash # Context length: 1M
    litellm_params:
      model: openrouter/deepseek/deepseek-v4-flash
      api_base: https://openrouter.ai/api/v1
      api_key: "os.environ/OPEN_ROUTER_API_KEY"
  - model_name: minimax/minimax-m3 # Context length: 1M
    litellm_params:
      model: openrouter/minimax/minimax-m3
      api_base: https://openrouter.ai/api/v1
      api_key: "os.environ/OPEN_ROUTER_API_KEY"
  - model_name: tencent/hy3-preview # Context length: 262K
    litellm_params:
      model: openrouter/tencent/hy3-preview
      api_base: https://openrouter.ai/api/v1
      api_key: "os.environ/OPEN_ROUTER_API_KEY"
  - model_name: anthropic/claude-opus-4.8 # Context length: 1M
    litellm_params:
      model: openrouter/anthropic/claude-opus-4.8
      api_base: https://openrouter.ai/api/v1
      api_key: "os.environ/OPEN_ROUTER_API_KEY"
  - model_name: "*"
    litellm_params:
      model: "openrouter/*"
      api_base: https://openrouter.ai/api/v1
      api_key: "os.environ/OPEN_ROUTER_API_KEY"

# https://openrouter.ai/google/gemini-3-flash-preview

# general_settings: 
#   master_key: sk-1234
  # database_url: "postgresql://test:123@192.168.1.156:5432/litellm"
  # store_prompts_in_spend_logs: true
  # maximum_spend_logs_retention_period: "3d"  
  # maximum_spend_logs_retention_interval: "1d"  

litellm_settings:
  success_callback: ["langfuse"]